### ISSUE TITLE
Questions on usage

### ISSUE THREAD

**Issue by landNull** [bertoost/ElasticEmail-Mailer#1]
First of all thank you for creating this plugin.

We're new to symfony so we're facing a vertical learning curve. We've tried to follow your instructions to the best of our abilities. 

We're attempting to use this plugin with mautic.

We installed the plugin using composer.

Set the DSN in the mautic DSN UI page. 

It fails with "The elastic email+API scheme is not supported"

We then tried setting MAILER_DNS as per the usage instructions, this did not work either. 

Is this something you can provide some insight on?

**Comment by bertoost** [comment]
Hi @landNull 

I have developed it for a Craft CMS plugin, which is based on the Symfony Mailer.
Therefore Symfony does support adding custom transports, but I just discovered I did not well on that for now. Since I have looked at other mailer integrations. But they are part of the core of the framework.
I have to make changes to make this work.

Tested things out for now; you have to register the factory yourself for now, by tagging it like this in your services.taml configuration file.

```yaml
bertoost\Mailer\ElasticEmail\Transport\ElasticEmailTransportFactory:
  tags:
    - { name: mailer.transport_factory }
```

I the nearby future I will check how to auto-tag this transport factory from the package itself. Thanks for pointing this out.

Regards, Bert

**Comment by landNull** [comment]
Thank you for following up so quickly. :D

**Comment by bertoost** [comment]
I have updated the package to work with Symfony natively. Can you try updating to version 1.1.0?
You can remove the above suggestion too. It's now handled by the package
Like to hear from you again.

**Comment by mia-geekgirl** [comment]
Hi there,

Thank you for the quick update! I upgraded via composer, but Mautic still isn't picking it up.

![brave_screenshot_info thehomeschoolquest com (2)](https://github.com/bertoost/ElasticEmail-Mailer/assets/166963680/2ad239a5-f0c5-42fa-9fec-98b56d67d8fd)

**Comment by bertoost** [comment]
I don't know about Mautic. But as far I can see, you should use "elasticemail+stmp" instead of "api" in the scheme name. The API is meant for connecting with API credentials (a key) instead of username/password of the SMTP service.
